/**
 * 事件类型清单（V3 数据字典 §20 / V4 §10.3）
 */
export const EventType = {
  // 回合类
  TURN_STARTED: 'TURN_STARTED',
  ACTION_PHASE_CHANGED: 'ACTION_PHASE_CHANGED',
  TURN_ENDED: 'TURN_ENDED',
  ROUND_ENDED: 'ROUND_ENDED',
  PLAYER_TURN_STATS_RESET: 'PLAYER_TURN_STATS_RESET',
  // 牌类
  CARD_PLAYED: 'CARD_PLAYED',
  CARD_DISCARDED: 'CARD_DISCARDED',
  CARDS_DRAWN: 'CARDS_DRAWN',
  DISCARD_RESHUFFLED_TO_DRAW: 'DISCARD_RESHUFFLED_TO_DRAW',
  DISCARD_PILE_RESHUFFLED: 'DISCARD_PILE_RESHUFFLED',
  // 巫师类
  WIZARD_MOVED: 'WIZARD_MOVED',
  WIZARD_ENTERED_CASTLE: 'WIZARD_ENTERED_CASTLE',
  WIZARD_IMPRISONED: 'WIZARD_IMPRISONED',
  WIZARD_RELEASED: 'WIZARD_RELEASED',
  // 塔类
  TOWER_SLICE_MOVED: 'TOWER_SLICE_MOVED',
  TOWER_STACK_REBUILT: 'TOWER_STACK_REBUILT',
  TOWER_SEALED: 'TOWER_SEALED',
  TOWER_UNSEALED: 'TOWER_UNSEALED',
  // 城堡类
  RAVEN_CASTLE_MOVED: 'RAVEN_CASTLE_MOVED',
  // 药水类
  POTION_FILLED: 'POTION_FILLED',
  POTION_SPENT: 'POTION_SPENT',
  // 法术类
  SPELL_CAST: 'SPELL_CAST',
  SPELL_EFFECT_APPLIED: 'SPELL_EFFECT_APPLIED',
  // 终局类
  ENDGAME_TRIGGERED: 'ENDGAME_TRIGGERED',
  WINNER_DETERMINED: 'WINNER_DETERMINED',
  GAME_ENDED: 'GAME_ENDED',
  // 初始化
  INIT_COMPLETED: 'INIT_COMPLETED',
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];
