/**
 * 规则错误码（V2 开发需求 §36 / V3 后端协议 §15）
 */
export const RuleErrorCode = {
  NOT_CURRENT_PLAYER: 'NOT_CURRENT_PLAYER',
  INVALID_PHASE: 'INVALID_PHASE',
  CARD_NOT_IN_HAND: 'CARD_NOT_IN_HAND',
  INVALID_WIZARD_TARGET: 'INVALID_WIZARD_TARGET',
  INVALID_TOWER_TARGET: 'INVALID_TOWER_TARGET',
  INVALID_MOVE_VALUE: 'INVALID_MOVE_VALUE',
  NO_LEGAL_TARGET: 'NO_LEGAL_TARGET',
  TARGET_CAPACITY_EXCEEDED: 'TARGET_CAPACITY_EXCEEDED',
  TOWER_CANNOT_LAND_ON_CASTLE: 'TOWER_CANNOT_LAND_ON_CASTLE',
  // 塔封印（T1.6 扩展机制：锁定塔不可移动）
  TOWER_IS_SEALED: 'TOWER_IS_SEALED',
  TOWER_ALREADY_SEALED: 'TOWER_ALREADY_SEALED',
  TOWER_NOT_SEALED: 'TOWER_NOT_SEALED',
  PLAYER_HAS_NO_WIZARD_ON_TOWER: 'PLAYER_HAS_NO_WIZARD_ON_TOWER',
  SPELL_LIMIT_REACHED: 'SPELL_LIMIT_REACHED',
  NOT_ENOUGH_FULL_POTIONS: 'NOT_ENOUGH_FULL_POTIONS',
  NO_FULL_POTION: 'NO_FULL_POTION',
  NO_EMPTY_POTION: 'NO_EMPTY_POTION',
  FILL_POTION_CONDITION_NOT_MET: 'FILL_POTION_CONDITION_NOT_MET',
  INVALID_SPELL_TARGET: 'INVALID_SPELL_TARGET',
  INVALID_SPELL: 'INVALID_SPELL',
  INVALID_CONFIG: 'INVALID_CONFIG',
  GAME_ALREADY_FINISHED: 'GAME_ALREADY_FINISHED',
  // 联机协议层（Phase 5）
  STATE_VERSION_CONFLICT: 'STATE_VERSION_CONFLICT',
  COMMAND_ALREADY_APPLIED: 'COMMAND_ALREADY_APPLIED',
} as const;

export type RuleErrorCode = (typeof RuleErrorCode)[keyof typeof RuleErrorCode];
